# =============================================================================
# Docker Compose Commands
# =============================================================================
# After applying Terraform, start the Docker environments:
#
# Ansible Runner Test:
#   cd docker-envs/ansible-runner-test && docker compose up -d
#
# Docker Runner (Common Tests):
#   cd docker-envs/docker-runner && docker compose up -d
#
# See docker-envs.tf for .env file generation
# =============================================================================


# =============================================================================
# Docker Environment Configuration
# =============================================================================
# Generates .env files for Docker Compose environments with runner tokens
# =============================================================================

# =============================================================================
# Ansible Runner Test Environment
# =============================================================================

# .env file for ansible-runner-test environment
resource "local_file" "ansible_runner_env" {
  filename = "${path.module}/docker-envs/ansible-runner-test/.env"
  content  = <<-EOT
# Generated by Terraform - DO NOT EDIT MANUALLY
# Run 'terraform apply' to regenerate this file

# Rundeck Server Configuration
RUNDECK_URL=http://host.docker.internal:4440

# Runner Image
RUNNER_IMAGE=${var.runner_image}

# Runner A Configuration
RUNNER_A_TOKEN=${rundeck_project_runner.ansible_runner_a.token}
RUNNER_A_ID=${rundeck_project_runner.ansible_runner_a.runner_id}

# Runner B Configuration
RUNNER_B_TOKEN=${rundeck_project_runner.ansible_runner_b.token}
RUNNER_B_ID=${rundeck_project_runner.ansible_runner_b.runner_id}
EOT

  file_permission = "0600"

  # Explicit dependency on runners being created first
  depends_on = [
    rundeck_project_runner.ansible_runner_a,
    rundeck_project_runner.ansible_runner_b
  ]
}

# =============================================================================
# Docker Runner Environment (Common Tests)
# =============================================================================

# .env file for docker-runner environment
resource "local_file" "docker_runner_env" {
  filename = "${path.module}/docker-envs/docker-runner/.env"
  content  = <<-EOT
# Generated by Terraform - DO NOT EDIT MANUALLY
# Run 'terraform apply' to regenerate this file

# Rundeck Server Configuration
RUNNER_RUNDECK_SERVER_URL=http://host.docker.internal:4440

# Runner Configuration
RUNNER_RUNDECK_SERVER_TOKEN=${rundeck_project_runner.common_runner.token}
RUNNER_RUNDECK_CLIENT_ID=${rundeck_project_runner.common_runner.runner_id}

# Runner Image and Platform
RUNNER_IMAGE=${var.runner_image}
RUNNER_PLATFORM=linux/amd64
EOT

  file_permission = "0600"

  # Explicit dependency on runner being created first
  depends_on = [
    rundeck_project_runner.common_runner
  ]
}

# =============================================================================
# Outputs for Docker Compose
# =============================================================================

output "docker_env_files" {
  description = "Generated .env file paths"
  value = {
    ansible_runner_test = local_file.ansible_runner_env.filename
    docker_runner       = local_file.docker_runner_env.filename
  }
}

# =============================================================================
# Usage Instructions
# =============================================================================
# After applying Terraform, start the Docker environments:
#
# Ansible Runner Test:
#   cd docker-envs/ansible-runner-test && docker compose up -d
#
# Docker Runner (Common Tests):
#   cd docker-envs/docker-runner && docker compose up -d
# =============================================================================
